weDevsOfficial/wp-user-frontend

lib/gateway/paypal.php

Paypal ssl security issue fix.
According to Paypal Security Notice, SSL is required for the paypal gateway to function properly. More details can be found below.
[https://www.paypal-notice.com/en/IPN-Verification-Postback-to-HTTPS/](url)

Paypal ssl fix

---

class/frontend-form-post.php

Some notification messages are not translation-ready; made 'em translatable.

Made Hard-Coded Strings Translation-ready

---

templates/dashboard/posts.php

Placeholder for Empty Featured Image was not displaying as the path is getting:
`wp-content/plugins/wp-user-frontend/templates/assets/images/no-image.png`
And that `templates/` part is wrong.

Fixed Placeholder for Empty Featured Image

---

includes/fields/class-field-image.php

Check for 'button_label' existence before using it, if it doesn't exist (older forms) fall back to label.
See issue #616

Check for 'button_label' existence before using it

---

includes/class-privacy.php

Adds support for group_description for privacy exporters which was added in WP5.3 through [WPCoreChangeset#45825](https://core.trac.wordpress.org/changeset/45825) and [WPCoreTracTicket#45491](https://core.trac.wordpress.org/ticket/45491)
Update Suggested Privacy Policy text to utilize privacy-policy-tutorial css class instead of wp-policy-help as it was deprecated. Also wrap the contents in the wp-suggested-text div to style the section to match WordPress. This follows from [WPCoreTrac#49282](https://core.trac.wordpress.org/ticket/49282) and although back-compat is being introduced in WP5.4 as of [WPChangeset#47112](https://core.trac.wordpress.org/changeset/47112) this change will better support users of WP5.1-5.4
This also removes the wrapping <div contenteditable="false"> as it's now …

Added Group Descriptions to Exporters and updated Privacy Policy guide to drop use of deprecated classes

---

assets/js/upload.js

If there is an image upload field and a file upload field in a form, a separate max file should be counted, but the two field combine to one max file.

Fix conflict file upload and image upload issue

---

admin/class-admin-subscription.php

Missing $ when declaring 'post_expiration_settings' variable.
Fix https://github.com/weDevsOfficial/wp-user-frontend/issues/904

Illigal variable declartion

---

includes/class-field-manager.php

When reviewing post post title, post content, post tags and categories fields are missing.
Fix https://github.com/weDevsOfficial/wp-user-frontend/issues/895

Fix post preview missing field

---

class/upload.php

If multiple files with the same name were saved, the previous file would be there but the next file would not be saved. This is why these problems have been created.
Fixes https://github.com/weDevsOfficial/wp-user-frontend/issues/916, https://github.com/weDevsOfficial/wp-user-frontend/issues/913

Fix file upload with same file name

---

admin/class-admin-settings.php

Upload mimes not working for uploading json file.
Fix https://github.com/weDevsOfficial/wp-user-frontend/issues/881

Fix upload mimes

---

includes/class-frontend-form-post.php

If the user is subscribed into a subscription pack, user is not redirected to the payment page after submitting a post that is set with Pay per Post.
Fix https://github.com/weDevsOfficial/wp-user-frontend/issues/844

Fix payment pay per post

---

includes/class-frontend-form-post.php
includes/class-frontend-render-form.php
wpuf-functions.php

If enabled is "Enable role base post" and the user role is not selected, the user can still view the post form.

Fix role base permission for accessing a post form

---

includes/class-frontend-render-form.php

If any post doesn't turn on 'Enable role base post', the post form couldn't be rendered in frontend.

Fix rolebase permission for post form

---

includes/class-frontend-render-form.php

If custom taxonomy field type is text and not exist the term, it couldn't save the term.
Fix: https://github.com/weDevsOfficial/wp-user-frontend/issues/946

Custom taxonomy input text

---

templates/submit-post.php

When select a default post form from settings, it couldn't show as default post form from the frontend account page.
Fix #978

Fix: Default post form is not showing on the frontend account

---

includes/class-frontend-form-post.php

If custom field of a post is an array, it sends an empty array as value for post notification and link show as plain text.
Fix: https://bitbucket.org/wedevs/wpuf-pro/issues/195/map-fields-data-is-not-rendering-on-the

Fix: post notification custom field value and link plain text

---

includes/fields/class-field-image.php

If make a compatible image field with acf image field, then update the post from backend keep empty the image field it shows a default image in frontend post edit form.
Fix: #945

Conflict with acf image field

---

includes/class-frontend-form-post.php

In order to make the line:
$post_author = get_current_user_id();
to be executed when the condition:
wpuf_user_has_roles( $this->form_settings['roles'] )
is true (the user has the compatible role to access the form)

Update class-frontend-form-post.php role base condition

---

assets/css/frontend-forms.css

Though there is no extra class or input type selector to select custom_html field, it's inheriting the initial width as 70% from [backend form builder](http://prntscr.com/vlors6) and [frontend preview/post page](http://prntscr.com/vlot1c). However, assigning width: 100%, fit-content, or auto; showing as it should be for the custom_html field.

70% width is affecting HTML content field's width

---

assets/vendor/sweetalert2/dist/sweetalert2.css

If there are no consequences, can we increase the z-index? As I found, the popup message is not showing with a third-party theme of a user.

Popup has a chance to get off-focus with a few 3rd party themes due to lower z-index

---

admin/form-builder/assets/js/form-builder.js
assets/js/wpuf-form-builder.js

Even though I had ‘Enable Payments’ unchecked, hidden below that I had ‘Enable Pay per post’ checked. Maybe it would be a good idea to ignore this setting if ‘Enable Payments’ is unchecked.

ignore all payment option if enable payments unchecked

---

assets/js/frontend-form.js
class/transactions-list-table.php
wpuf-functions.php

In WP Dashboard > User Frontend > Transaction, new label added as 'All'.
A JS deprecated function is replaced (not related to this issue).
fix [#216](https://github.com/weDevsOfficial/wpuf-pro/issues/216) (in pro)

fix: All label added for transactions page

---

assets/js/wpuf-login-widget.js
includes/free/class-login.php

Reset password message now showing when request coming from AJAX, such as sidebar widget.
fix #1244

fix: Reset password message requesting from AJAX

---

assets/css/frontend-forms.css
assets/less/frontend-forms.less

Invalid predefined (!important) width causing the T&C checkbox invisible for default "terms_and_conditions" meta ([https://prnt.sc/22rav3a](https://prnt.sc/22rav3a)). You need to change the default meta_key of the T&C field to make the checkbox visible on the frontend.

Redundant CSS with the default T&C field's meta causing the checkbox invisible

---

class/encryption-helper.php
includes/free/class-registration.php
templates/registration-form.php
wpuf-functions.php
wpuf.php

Admin can set the short-code with `role` attribute. Example: `[wpuf-registration role='editor']`. Any role will work except `administration`. If admin set `[wpuf-registration role='administration']`, it will set the user role to the default user role from `Settings > General Settings > New User Default Role`
Another [testing scenario](https://wedevs.slack.com/archives/G17RY7NVB/p1662374469651519). Needs to test with PHP version 5.6 and PHP 8

fix: [wpuf-registration] short-code encryption update

---

class/upload.php

A `time hash` was added for this [issue](https://github.com/weDevsOfficial/wp-user-frontend/issues/809) before. It was adding a `time hash` after the file name to prevent duplication. As there is already a check for duplicate files by `file name` and `file size`, the `time hash` is removed.
Now the scenarios are:
1. If uploaded files have the same name that exists in the WP media library, it will add an incrementing number like `-1` as per WordPress.
2. If the uploaded file name (with extension) and size match with a file with the WP media library, it won't upload the new file and link the previous file to this post.
fix [#485](https://github.com/weDevsOfficial/wpuf-pro/issues/485) in pro

fix: random number added on file name after uploading

---

assets/js/frontend-form.js
assets/less/frontend-forms.less
includes/class-frontend-form-post.php
includes/fields/class-field-textarea.php
wpuf.php

- Individually check for `word limit` and `char limit` in richtextarea and teeny rich textarea
- Individually check for `word limit` and `char limit` in textarea
**Testing instruction**: please run `grunt uglify` before testing
fix [#492](https://github.com/weDevsOfficial/wpuf-pro/issues/492)

fix: content restriction issues on paste

---

admin/class-admin-subscription.php
assets/js/subscriptions.js

- enable the `Expiration Mail` option in the subscription settings
- change the wording for updating subscription alert

tweaking for v3.6.1

---

admin/form-builder/assets/less/form-builder.less
admin/form-builder/class-wpuf-admin-form-builder.php
admin/form-template.php
assets/less/frontend-forms.less

1. Dropdown item options were not showing when LearnPress is installed.
2. `wpuf-form-builder.css` was loading multiple times
3. removed `font-family` assigning style from WPUF. font-family should come from the theme or WP core.
**How to reproduce:**
1. Install & Activate WP User Frontend free plugin
2. Install & Activate the Learnpress LMS plugin: https://wordpress.org/plugins/learnpress/
3. Add a dropdown field on the post form > Edit dropdown field > Field options > Item Options not appearing
Necessary [Screenshot](https://prnt.sc/tsFeCc9judL_)

Fix: style conflict with LearnPress

---

wpuf-functions.php

The `Bank Payment Success Page` redirection setting was not working as expected. It’s honoring the `Payment Success Page` redirection instead the `Bank Payment Success Page` redirection.
We have two success pages for the Payment procedure.
1. The `Payment Success Page` which is for the online payment gateways (Stripe and Credit cards)
2. The `Bank Payment Success Page` is for the `Bank Payment/Manual-Offline payment` method.
However, in both cases, it honors the first option `Payment Success Page.`
[Problem video here](https://somup.com/c31rFMtdNA)
**Expected behavior:**
If you select the `Bank Payment` option during the purchase of the subscription it should redirect you to the 2nd option called `Bank Payment Success Page`.
Now the redirection priority is as followed from the top …

Redirection added for bank payment success page

---

admin/form-builder/assets/js/form-builder.js
assets/css/admin.css
assets/js/wpuf-form-builder.js
assets/less/admin.less

In the WPUF form builder, there was a problem adding multiple HTML fields inside the column field. Details [video](https://www.loom.com/share/e780c77420354555b09b32ebb7cec730)

fix: multiple HTML field inside column field

---

admin/class-plugin-upgrade-notice.php
wpuf.php

We can now show notice/message to the user before updating WP User Frontend.
Image:

enhance: add custom note on plugin update page

---

assets/js/wpuf-login-widget.js
class/render-form.php
includes/class-acf.php
includes/class-billing-address.php
includes/class-field-manager.php
includes/class-login-widget.php
includes/class-whats-new.php
includes/fields/class-field-post-tags.php
wpuf-functions.php

add missing nonce validation for ajax actions.
**Things to test:**
- whats new notice dismiss
- ajax tag search
- ACF compatibility buttons
- Login/Logout widget
Related [discussion](https://wedevs.slack.com/archives/G17RY7NVB/p1692275546518139)

fix: nonce validation for ajax actions

---

Lib/Appsero/Client.php
Lib/Appsero/Insights.php
Lib/Appsero/License.php
Lib/WeDevs_Insights.php
composer.json
composer.lock
includes/Admin/Subscription.php
includes/Ajax/Frontend_Form_Ajax.php
includes/Traits/TaxableTrait.php
includes/class-frontend-render-form.php
wpuf-functions.php
wpuf.php

final tweaks

---

includes/Free/Simple_Login.php

When recaptcha is enabled and you try to log in the following error page comes up 'A critical error has occurred on this site.'
fix #1411

fix: login with recaptcha gives error

---

includes/Admin/Forms/Post/Templates/Post_Form_Template_Events_Calendar.php
includes/Admin/Forms/Post/Templates/Post_Form_Template_Post.php
includes/Admin/Forms/Post/Templates/Post_Form_Template_WooCommerce.php

when selecting a registration form template, in form settings > General > Form Template not automatically selecting.

fix: default form template not selecting

---

assets/css/frontend-forms.css
assets/less/frontend-forms.less
includes/Fields/Form_Field_Post_Taxonomy.php

An error occurs when the user switches a taxonomy field to “multi-select”.
issue [details](https://wedevs.slack.com/archives/G17RY7NVB/p1705263230677249)

fix: error on multi select form custom taxonomy

---

templates/registration-form.php

Unregistered users visiting the page with shortcode: [wpuf-registration]
setting enabled to redirect to subscriptions before register. When an unregistered user clicks sign up on a pack, the page throws: There has been a critical error on this website.

fix: frontend registration form is not showing

---

includes/Free/Simple_Login.php
templates/login-form.php
templates/lost-pass-form.php
templates/reset-pass-form.php

Using Forgot-password and setting new password is not working ---> The old password is still being used to perform login-action and the new-set password is not working at all
fix [#558](https://github.com/weDevsOfficial/wpuf-pro/issues/558)

fix: reset password not working

---

Lib/WeDevs_Settings_API.php
wpuf-functions.php

some tweaks for `v4.1.1` release.
1. fix search on settings page. after PCP fixes it was broken
2. remove events calendar template as we doesn't fully support Events Calendar integration fully after their breaking change on version 6

tweak: for v4.1.1

---

includes/Fields/Form_Field_Post_Content.php

Close #1469 
1. Fixed HTML structure to ensure proper rendering of form fields by adding a missing closing tag. (div)

Fix: Add missing closing div in Post Content form field

---

includes/Admin/views/post-forms-list-table-view.php

* **Style**
* Updated the main container styling in the post forms list table view to hide overflow content, which may affect how content is displayed or clipped within this section.

fix: wpuf-post-forms-list-table-overflow-hidden
