weDevsOfficial/wp-user-frontend

- admin/form.php
- assets/css/frontend-forms.css
- assets/css/frontend-forms.less
- assets/js/formbuilder.js
- assets/js/frontend-form.js
- includes/free/form.php
- wpuf.php
> Free Version Updated

- assets/css/frontend-forms.css
- assets/css/frontend-forms.less
- assets/js/frontend-form.js
- languages/wpuf.pot
> Pull Request

- admin/form.php
- assets/js/frontend-form.js
- includes/free/form.php
Now the progressbar is only visible if multistep is active and the mode is progressive
> progressbar made appeared in multistep->progressive mode

- class/render-form.php
- wpuf-functions.php
Category field in form builder in ajax type is now working
> Category field in form builder in ajax type is now working

- class/frontend-form-post.php
- includes/free/edit-user.php
replace depricated function wp_new_user_notification by wp_send_new_user_notification
> Please replace the deprecated function

- admin/posting.php
- admin/settings-options.php
- wpuf.php
API settings added to render Google maps properly.
> gMap API settings Added

- class/render-form.php
Resolves tareq1988/WP-User-Frontend#67
> Remove prepend namespace from form label

- class/frontend-form-post.php
fixed post content key for saving post data as draft
> fix missing data when saving draft post

- includes/free/edit-user.php
Make users filterable, by introducing filter 'wpuf_show_users'
> Use WordPress function to get users and filter them as well.

- class/subscription.php
- includes/class-user-subscription.php
Issues Fixed:
1. github issue#236 fixed
2 . subscription pack display order fixed
> fix for packs with unlimited post +display subscription order

- assets/js/wpuf-admin.js
- class/subscription.php
Added subscription notification event on deactivation  and updated subscription notification js
> Bugfix/fixes 2.8.0

- templates/dashboard/edit-profile.php
> Fix edit profile page was not working

- class/subscription.php
> Fixed post form infinite loop issue

- class/frontend-form-post.php
- class/render-form.php
> Showing form schedul before rendering post form, Fixed #374

- templates/registration-form.php
Label "First" and "Last" is hard-coded, and not translation-ready.
> Made Hard-Coded Strings Translation-ready

- templates/dashboard.php
Warning-> https://jumpshare.com/v/3XGObU6E1rD2gvgzP58F
> fixed the warning on the user dashboard(added empty label checking)

- assets/js/frontend-form.js
- class/render-form.php
- wpuf.php
tinymce wasn't enqueued in frontend and never initialized.
onKeyDown & onPaste shows errrors if tinyMCE isn't initialized.
getBody(), doesn't exists.
> Frontend JS error fix

- wpuf.php
> Retain default when determining whether to display the admin bar

- templates/dashboard/edit-profile.php
For custom wp-includes location
> Standard includes URL

- lib/appsero/Client.php
- lib/appsero/Insights.php
- lib/appsero/License.php
- lib/appsero/Updater.php
Update Appsero client with latest files
> Update tracker SDK

- assets/css/frontend-forms.css
- assets/less/frontend-forms.less
- templates/dashboard.php
- templates/dashboard/posts.php
1. set form fields width to 100% of it's container
2. added overflow scroll for tables and added parent div for making scrollable.
3. fix subscription packs layout breaking issue
> fix responsive issues

- class/frontend-form-post.php
- includes/class-form.php
wp-content/plugins/wp-user-frontend/includes/class-form.php | 235
wp-content/plugins/wp-user-frontend/class/frontend-form-post.php | 110
added missing text domain
> fix:added missing text-domain

- includes/free/class-login.php
- templates/reset-pass-form.php
> Fix reset password form issue.

- includes/free/class-login.php
- templates/reset-pass-form.php
> Fix reset password form processes

- templates/dashboard.php
Enhance the post delete message.
Fix https://github.com/weDevsOfficial/wp-user-frontend/issues/588
> Enhance delete post message

- includes/fields/class-field-sectionbreak.php
It was not stayed full width.
Fix https://github.com/weDevsOfficial/wp-user-frontend/issues/934
> Fix align section break field

- includes/class-frontend-form-post.php
Add post edit link. This link will redirect to post edit form in frontend.
> Add post edit link

- includes/free/class-login.php
Don't show any confirmation message after password reset email send.
Fix: #938
> Fix: Lost password reset email message

- includes/class-field-manager.php
Couldn't render feature image field when post form preview.
> Fix: Missing featured image field when post form preview

- assets/js/billing-address.js
- wpuf-functions.php
When change billing address state, tax rate couldn't change.
> Fix: Change tax rate when select another state

- assets/js/frontend-form.js
Google map validation doesn't work.
Fix: https://bitbucket.org/wedevs/wpuf-pro/issues/192/google-map-field-is-not-meeting-with-the
> Fix: Google map validation doesn't work

- wpuf-functions.php
Otherwise, there is no way we can get the subject of the mail from this filter
> Add subject to filter

- admin/posting.php
Unlocking post from backend is not allowing the user to edit the post from frontend
Fix #990
> Fix: Post edit unlock issue

- includes/class-frontend-form-post.php
After updating post redirect to payment page.
Fix: https://bitbucket.org/wedevs/wpuf-pro/issues/215/pay-per-post-subscription-is-redirecting
> Fix: redirect payment page after post updating

- class/payment.php
When an invalid  subscription id passed to URL it shows  "enjoy the message  free package"
Fix: #836
> Invalid subscription

- admin/form-builder/assets/js/components/form-column_field/index.js
issue create on pro [Here](https://github.com/weDevsOfficial/wpuf-pro/issues/246)
> fix: column field width fixed #246

- wpuf-functions.php
Add Mauritian Rupee for currency (http://prntscr.com/10ptofv).
> Add Mauritian Rupee for currency

- class/payment.php
Companion [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/310)
Users shouldn't got to payment directly. either by copy past payment url or from another price table list which is not our default subscription page.
> payment without login handled

- assets/css/frontend-forms.css
- assets/js/frontend-form.js
- assets/less/frontend-forms.less
- templates/dashboard/posts.php
Changes requested from hasinur [PR](https://github.com/weDevsOfficial/wp-user-frontend/pull/1079)
> Account page UI update

- wpuf-functions.php
Details [Here](Can't edit post/registration form after installing wpuf pro 3.4.7
)
> wpuf preview page inconsistence with form builder

- assets/css/frontend-forms.css
- assets/less/frontend-forms.less
Details [HERE](https://github.com/weDevsOfficial/wpuf-pro/pull/326)
Please follow image.
> TOC checkbox width issue fixed

- includes/class-frontend-render-form.php
companion [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/325)
> map field full address taken in line with acf map

- class/frontend-account.php
- templates/dashboard/dashboard.php
- wpuf-functions.php
user can change account section menu slug i.e 
`add_filter('wpuf_account_sections',function ($sections){
$sections['post']['label'] = 'List';
$sections['subscription']['label'] = 'Membership';
return $sections;
},999);`
> existing account section filter improved for client modification

- admin/settings-options.php
- wpuf-functions.php
Companion [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/342)
> controller added for various email notification

- admin/form-builder/assets/js/form-builder.js
- assets/js/wpuf-form-builder.js
[Here](https://github.com/weDevsOfficial/wpuf-pro/issues/366)
> prevent modal for custom field in reg form fixed

- wpuf-functions.php
2 new functions introduced.
wpuf_get_image_sizes_array: returns an array representation for 'thumbnail', 'medium', 'large', 'medium_large' etc. images sizes.
wpuf_pagination: returns a pagination html with dynamic pagenumber, prev-next button
> fix: New functions introduced

- assets/js/frontend-form.js
Also We were checking the required field with the field name. and the field name set by the meta_key. Now checking with id prefix 'wpuf-map'
Related [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/378) : Conditional required fields error
> fix: Required google map field is not working

- lib/gateway/bank.php
- wpuf-functions.php
[Detail](https://ibb.co/Q89ksvH)
> tax calculated properly for bank and transaction meta handle

- admin/form-builder/assets/js/form-builder.js
- assets/js/wpuf-form-builder.js
Companion [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/375)
> meta key enhanced for user email notification

- assets/js/wpuf-admin.js
- includes/free/class-login.php
Companion [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/384)
> activated email template enhanced

- class/payment.php
- lib/class.settings-api.php
- lib/gateway/bank.php
- lib/gateway/paypal.php
Enhancement payment instructions settings fields.
> Payment instructions

- assets/js/frontend-form.js
- includes/class-frontend-form-post.php
- includes/fields/class-field-textarea.php
Word/Character count limit not working
fix #1225
> fix: Content restriction not working

- assets/js/frontend-form.js
Validation added for invalid email and URL formats.
fix #1237
> fix: Validation for email and URL

- class/frontend-account.php
- templates/dashboard/posts.php
A preview option is added for drafted or unpublished posts in the frontend user profile.
fix [this issue in pro](https://github.com/weDevsOfficial/wpuf-pro/issues/358)
> fix: Preview option added in user profile

- wpuf-functions.php
Companion [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/398)
> [FREE] email style handled

- admin/posting.php
- includes/fields/class-abstract-fields.php
Companion [PR](https://github.com/weDevsOfficial/wpuf-pro/pull/399)
> [PRO] Fix/conditional logic not working on metabox

- assets/less/frontend-forms.less
Note for testing: Remember to run
`composer i`
`composer du -o`
`npm i`
`grunt` command after pulling.
Companion [PR ](https://github.com/weDevsOfficial/wpuf-pro/pull/468)
> Button style updated for multistep forms

- admin/form-builder/assets/js/components/field-option-data/index.js
- assets/js/wpuf-form-builder-components.js
Issue details: [#481](https://github.com/weDevsOfficial/wpuf-pro/issues/481)
> dropdown field ordering fixed for float number

- assets/css/admin.css
- assets/css/admin/wpuf-module.css
- assets/js/wpuf-admin.js
- assets/less/admin.less
- includes/free/loader.php
- includes/free/subscription.php
testing instruction: run `grunt release` after pull
fix [#493](https://github.com/weDevsOfficial/wpuf-pro/issues/493)
> enhance: add responsiveness to the upgrade-to-pro

- lib/appsero/Client.php
- lib/appsero/Insights.php
- lib/appsero/License.php
- lib/appsero/Updater.php
update appsero sdk to `v1.2.2`
> update appsero sdk

- includes/class-dokan-integration.php
- wpuf-functions.php
- wpuf.php
> fix: post submission for dokan vendors

- assets/less/frontend-forms.less
- wpuf.php
- fix: error if `dokan` is not installed.
- style fixed for different `display settings` in `form setting`
please run `grunt less` before testing
fix #1337
> fix: error if dokan not installed

- class/payment.php
- lib/gateway/paypal.php
- wpuf-functions.php
PayPal transactions are not visible on the WPUF Transaction page. Details [here](https://wedevs.slack.com/archives/G17RY7NVB/p1678822310054919)
> fix: paypal transaction not showing

- wpuf-functions.php
The required field doesn't work for the predefined category field in the Post form. Video details [here](https://www.loom.com/share/720895647b0b49d2a2839dbebc29b0a1)
issue in pro [#496](https://github.com/weDevsOfficial/wpuf-pro/issues/496)
> fix: predefined category field not working

- admin/promotion.php
Dashboard Promotional banner design updated from [this](https://prnt.sc/u3qIDZTNKKr7) to [that](https://prnt.sc/l5R6J4IyCyH4)
> Update the promo notice design

- includes/fields/class-field-post-taxonomy.php
Related PR: [#466](https://github.com/weDevsOfficial/wpuf-pro/pull/466)
> fix: conditional field enhancement

- admin/class-admin-subscription.php
- includes/fields/class-field-post-taxonomy.php
(Users>Profile) Logged in as Admin: Doesn't show expiration time for Subscription.
fix [#501](https://github.com/weDevsOfficial/wpuf-pro/issues/501)
> fix: expiration time not showing for admin

- admin/posting.php
a critical error was showing when editing the user information.
Problem [details](https://wedevs.slack.com/archives/G17RY7NVB/p1683137374879289)
> fix: fatal error when editing user profile

- assets/js/wpuf-admin.js
WPUF conflicts with the Classic editor Plugin. The user can’t publish a post or page on it when WP User Frontend Plugin is active. It stays as a draft.
Reference [video](https://www.loom.com/share/6901610c4a334513800e4d4c94f6573c)
> fix: post not publishing for classic editor

- includes/class-frontend-render-form.php
- wpuf-functions.php
When a taxonomy field(ex: category, custom taxonomy) saved as type checkbox, data was not showing after saving a post.
fix #1377
> fix: taxonomy data not showing for checkbox

- assets/js/frontend-form.js
- assets/js/upload.js
- class/upload.php
- templates/dashboard/posts.php
delete upload file even after selecting cancel.
fix #1316
> fix: delete upload file even after cancel

- assets/js/wpuf-admin.js
JS error fixed for classic editor, custom post types in both visual and text editing mode. 
fix #1372 #1382
> fix: shortcode restriction checking

- admin/class-admin-settings.php
- admin/class-admin-subscription.php
- admin/form-builder/class-wpuf-admin-form-builder-ajax.php
- admin/posting.php
- admin/promotion.php
- class/frontend-account.php
- includes/class-acf.php
- includes/class-frontend-form-post.php
- includes/class-frontend-render-form.php
- includes/class-whats-new.php
- wpuf.php
Things to test: 
- import forms
- delete user package
- save WPUF form
- preview WPUF form
- clear schedule lock
- dismiss review notice
- dismiss promotional offer
> fix: add capabilities check on AJAX actions

- includes/Ajax/Frontend_Form_Ajax.php
- includes/Free/Free_Loader.php
for guest post, backend validation added for checking the guest email
> fix: handle email for guest post

- class/render-form.php
- includes/Fields/Form_Field_Image.php
- includes/Render_Form.php
fix: cannot edit posts from the frontend using the latest version of WPUF.
Reference [Video](https://www.loom.com/share/1522bf45a72144459240d4d155950d01)
> fix: ajax image upload

- Lib/WeDevs_Insights.php
Completing the Setup wizard process last step generates error
Scenario:
Activate WPUF-Lite
Click Continue and finish setup > error generated
fix [#547](https://github.com/weDevsOfficial/wpuf-pro/issues/547)
> fix: error in setup wizard

- includes/Admin.php
- includes/Frontend.php
Admin Bar Visibility and Access Configuration Not Working as Expected
fix [#549](https://github.com/weDevsOfficial/wpuf-pro/issues/549)
> fix: Admin Bar Visibility and Access

- includes/Frontend/Frontend_Form.php
- includes/Traits/FieldableTrait.php
WC attribute support from frontend form. issue [details](https://d.pr/v/dBufQh)
> fix: WC attribute support from frontend form

- includes/Fields/Field_Contract.php
- includes/Fields/Form_Field_Featured_Image.php
- includes/Fields/Form_Field_Image.php
When our forms shortcode is placed inside a page builder like `Beaver Builder`, file uploads was not working.
> fix: file upload problem using page builders

- includes/Admin/Forms/Field_Manager.php
- includes/Traits/TaxableTrait.php
error when using CPT on post form.
fix #1441
> fix: error when using CPT on post form

- includes/Free/Simple_Login.php
Registered users can still log in without approval from Admin. [details](https://wedevs.slack.com/archives/G17RY7NVB/p1707337219202799)
> fix: pending user can log in

- includes/Ajax/Frontend_Form_Ajax.php
Issue:
When a post form is created --> Notification sends Edit link --->>> Which is not working
fixes [#573](https://github.com/weDevsOfficial/wpuf-pro/issues/573)
> fix: edit link on mail not working

- includes/Admin.php
- includes/Admin/Admin_Tools.php
- includes/Admin/Menu.php
Issue:
Cannot Import forms in WPUF > Tools
closes [#583](https://github.com/weDevsOfficial/wpuf-pro/issues/583)
> fix: form import is not working

- Lib/Gateway/Paypal.php
- Lib/WeDevs_Settings_API.php
- assets/css/admin.css
- assets/css/admin/form-builder.css
- assets/js-templates/form-components.php
- assets/less/admin.less
- includes/Admin/views/post-forms-list-table-view.php
> tweak: for 4.1.4 release
